import { auth } from '@/app/config/firebase.config';
import * as AuthSession from 'expo-auth-session';
import * as Google from 'expo-auth-session/providers/google';
import Constants from 'expo-constants';
import * as WebBrowser from 'expo-web-browser';
import { GoogleAuthProvider, signInWithCredential } from 'firebase/auth';

WebBrowser.maybeCompleteAuthSession();

/**
 * Helper to get Google auth request config
 * You should configure these in your app.json or environment
 * For Expo, you typically need:
 * - clientId: The web client ID from Firebase Console
 * - redirectUri: The redirect URI (usually auto-generated by expo-auth-session)
 * - androidClientId: Android client ID (optional, for native Android)
 * - iosClientId: iOS client ID (optional, for native iOS)
 */
export function getGoogleAuthConfig(): Google.GoogleAuthRequestConfig {
  // Get from environment or use defaults
  // You'll need to set these up in your Firebase Console and app.json
  const webClientId = Constants.expoConfig?.extra?.googleWebClientId || '540547551554-gvm1hc69v0c8e906vk1l0hlo16tq09qk.apps.googleusercontent.com';
  
  // For Expo, generate the redirect URI
  const redirectUri = AuthSession.makeRedirectUri();
  
  console.log('Google OAuth Config:', {
    clientId: '540547551554-gvm1hc69v0c8e906vk1l0hlo16tq09qk.apps.googleusercontent.com',
    redirectUri: redirectUri,
  });
  
  const config: Google.GoogleAuthRequestConfig = {
    clientId: webClientId,
    redirectUri: redirectUri,
  };

  // Add platform-specific client IDs if available
  if (Constants.expoConfig?.extra?.googleAndroidClientId) {
    config.androidClientId = Constants.expoConfig.extra.googleAndroidClientId;
  }
  if (Constants.expoConfig?.extra?.googleIosClientId) {
    config.iosClientId = Constants.expoConfig.extra.googleIosClientId;
  }

  return config;
}

/**
 * Google Sign-In hook - returns the prompt function
 * This should be used inside a React component
 */
export function useGoogleLogin() {
  const config = getGoogleAuthConfig();
  const [request, response, promptAsync] = Google.useAuthRequest(config);

  const login = async (): Promise<{ user: any; idToken: string }> => {
    const result = await promptAsync();
    
    if (result.type === 'cancel') {
      throw new Error('Google login was cancelled');
    }
    
    if (result.type !== 'success') {
      console.error('Google auth result:', result);
      if (result.type === 'error') {
        const errorMsg = result.error?.message || result.error?.code || 'Unknown error';
        throw new Error(`Google login failed: ${errorMsg}`);
      }
      throw new Error('Google login failed');
    }

    if (!result.authentication?.idToken) {
      throw new Error('No ID token received from Google. Please check your OAuth configuration.');
    }

    try {
      // Create Firebase credential
      const credential = GoogleAuthProvider.credential(result.authentication.idToken);
      
      // Sign in to Firebase
      const userCred = await signInWithCredential(auth, credential);
      const idToken = await userCred.user.getIdToken();

      return {
        user: userCred.user,
        idToken,
      };
    } catch (error: any) {
      console.error('Firebase credential error:', error);
      if (error.code === 'auth/operation-not-allowed') {
        throw new Error('Google Sign-In is not enabled in Firebase Console. Please enable it in Authentication → Sign-in method.');
      }
      throw error;
    }
  };

  return { login, loading: request === null };
}
